//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.CMSWebParts.CardLab.Buxx.Account {
    
    
    public partial class CardTransactionsWebPart {
        
        /// <summary>
        /// _teenListTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.TeenListTab _teenListTab;
        
        /// <summary>
        /// _listRetrieveTransactions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.ListRetrieveTransactions _listRetrieveTransactions;
    }
}
