//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.CMSWebParts.CardLab.Buxx.Account {
    
    
    public partial class TeenOverviewWebPart {
        
        /// <summary>
        /// _teenListTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.TeenListTab _teenListTab;
        
        /// <summary>
        /// _teenSummaryViewer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.TeenSummaryViewer _teenSummaryViewer;
        
        /// <summary>
        /// _listRecentTransactions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.ListRecentTransactions _listRecentTransactions;
        
        /// <summary>
        /// _transactionLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink _transactionLink;
        
        /// <summary>
        /// _listPendingLoads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CMSApp.Controls.Buxx.Account.ListPendingLoads _listPendingLoads;
        
        /// <summary>
        /// _pendingLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink _pendingLink;
    }
}
